api/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'todolists', views.TodoListViewSet)
router.register(r'todos', views.TodoViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
]

lists/urls.py
from django.urls import path

from lists import views

app_name = 'lists'
urlpatterns = [
    path('', views.index, name='index'),
    path('todolist/<int:todolist_id>/', views.todolist, name='todolist'),
    path('todolist/new/', views.new_todolist, name='new_todolist'),
    path('todolist/add/', views.add_todolist, name='add_todolist'),
    path('todo/add/<int:todolist_id>/', views.add_todo, name='add_todo'),
    path('todolists/', views.overview, name='overview'),
]

todolist/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('lists.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

lists/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone


class TodoList(models.Model):
    title = models.CharField(max_length=128, default='untitled')
    created_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, null=True, related_name='todolists', on_delete=models.CASCADE)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.title

    def count(self):
        return self.todos.count()

    def count_finished(self):
        return self.todos.filter(is_finished=True).count()

    def count_open(self):
        return self.todos.filter(is_finished=False).count()


class Todo(models.Model):
    description = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now=True)
    finished_at = models.DateTimeField(null=True)
    is_finished = models.BooleanField(default=False)
    creator = models.ForeignKey(User, null=True, related_name='todos', on_delete=models.CASCADE)
    todolist = models.ForeignKey(TodoList, related_name='todos', on_delete=models.CASCADE)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.description

    def close(self):
        self.is_finished = True
        self.finished_at = timezone.now()
        self.save()

    def reopen(self):
        self.is_finished = False
        self.finished_at = None
        self.save()

lists/forms.py
from django import forms


def widget_attrs(placeholder):
    return {'class': 'u-full-width', 'placeholder': placeholder}


def form_kwargs(widget, label='', max_length=128):
    return {'widget': widget, 'label': label, 'max_length': max_length}


class TodoForm(forms.Form):
    description = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('Enter your todo'))
        )
    )


class TodoListForm(forms.Form):
    title = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(
                attrs=widget_attrs('Enter a title to start a new todolist')
            )
        )
    )

lists/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from lists.models import TodoList, Todo
from lists.forms import TodoForm, TodoListForm


def index(request):
    return render(request, 'lists/index.html', {'form': TodoForm()})


def todolist(request, todolist_id):
    todolist = get_object_or_404(TodoList, pk=todolist_id)
    if request.method == 'POST':
        redirect('lists:add_todo', todolist_id=todolist_id)

    return render(
        request, 'lists/todolist.html',
        {'todolist': todolist, 'form': TodoForm()}
    )


def add_todo(request, todolist_id):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            user = request.user if request.user.is_authenticated else None
            todo = Todo(
                description=request.POST['description'],
                todolist_id=todolist_id,
                creator=user
            )
            todo.save()
            return redirect('lists:todolist', todolist_id=todolist_id)
        else:
            return render(request, 'lists/todolist.html', {'form': form})

    return redirect('lists:index')


@login_required
def overview(request):
    if request.method == 'POST':
        return redirect('lists:add_todolist')
    return render(request, 'lists/overview.html', {'form': TodoListForm()})


def new_todolist(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            # create default todolist
            user = request.user if request.user.is_authenticated else None
            todolist = TodoList(creator=user)
            todolist.save()
            todo = Todo(
                description=request.POST['description'],
                todolist_id=todolist.id,
                creator=user
            )
            todo.save()
            return redirect('lists:todolist', todolist_id=todolist.id)
        else:
            return render(request, 'lists/index.html', {'form': form})

    return redirect('lists:index')


def add_todolist(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            user = request.user if request.user.is_authenticated else None
            todolist = TodoList(title=request.POST['title'], creator=user)
            todolist.save()
            return redirect('lists:todolist', todolist_id=todolist.id)
        else:
            return render(request, 'lists/overview.html', {'form': form})

    return redirect('lists:index')

lists/templates/lists/index.html
{% extends "base.html" %}

{% block body %}
<section class="header">
  <h2 class="title">Dead simple Todolists.</h2>
  <div class="row">
    <div class="three columns value-prop"></div>
    <div class="six columns">
      <form action="{% url 'lists:new_todolist' %}" method=post>
        {% csrf_token %}
        <dl>
          <dd>{{ form }}
          <dt><input type="submit" class="button button-primary" value="Start one now">
        </dl>
      </form>
    </div>
  </div>
</section>
{% endblock %}

lists/templates/lists/overview.html
{% extends "base.html" %}

{% load static %}
{% load lists_extras %}

{% block js %}
<script src="{% static 'lists/js/jquery.tablesorter.min.js' %}"></script>
<script type="text/javascript" id="js">
$(document).ready(function() {
  var timeExtraction = function(node) {
    if ($(node).attr('data-time-in-seconds') !== undefined) {
      return '-' + node.getAttribute('data-time-in-seconds');
    } else {
      return node.innerHTML;
    }
  }
  $("#todolist-overview-table").tablesorter({
    textExtraction: timeExtraction
  });
});
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'lists/css/table.css' %}"> {% endblock %}

{% block body %}
<section class="header">
  <h2 class="title">Todolist overview</h2>
  <div class="row">
    <div class="three columns value-prop"></div>
    <div class="six columns">
      <form action="{% url 'lists:add_todolist' %}" method=post>
        {% csrf_token %}
        <dl>
          <dd>{{ form }}
          <dt><input type="submit" value="Submit">
        </dl>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="u-full-width">
      <h6 class="docs-header todolist-overview">All your todolists</h6>
      <table id="todolist-overview-table" class="tablesorter">
        <thead>
          <tr>
            <th class='todolist-title'>Todolist title</th>
            <th># Open</th>
            <th># Finished</th>
            <th class="datetime">Created at</th>
          </tr>
        </thead>
        <tbody>
          {% for todolist in user.todolists.all %}
          <tr>
            <td class='todolist-title'><a href="{% url 'lists:todolist' todolist_id=todolist.id %}">{{ todolist.title }}</a></td>
            <td>{{ todolist.count_open }}</td>
            <td>{{ todolist.count_finished }}</td>
            <td data-time-in-seconds="{{ todolist.created_at|in_seconds }}">{{ todolist.created_at|humanize }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock %}

lists/templates/lists/todolist.html
{% extends "base.html" %}

{% load static %}

{% block js %}
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<script src="{% static 'lists/js/lists.js' %}"></script>
{% endblock %}

{% block body %}
<section class="header">
  <div class="row">
    <div class="three columns value-prop"></div>
    <div class="six columns">
      <div class="title">{{todolist.title}}</div>
      <form action="{% url 'lists:add_todo' todolist.id %}" method=post>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
      </form>
    </div>
    <div class="row">
      <div class="one-half column open-todos">
        <h6 class="docs-header open-todos">{{ todolist.count_open }} open</h6>
        <ul>
          {% for todo in todolist.todos.all %}
            {% if not todo.is_finished %}
              <li><input type="checkbox" id="checkbox" data-todo-id="{{ todo.id }}"> {{ todo.description }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      <div class="one-half column finished-todos">
        <h6 class="docs-header finished-todos">{{ todolist.count_finished }} finished</h6>
        <ul>
          {% for todo in todolist.todos.all %}
            {% if todo.is_finished %}
            <li><input type="checkbox" id="checkbox" data-todo-id="{{ todo.id }}" checked="checked"> {{ todo.description }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock %}